<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class TodoAddRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'post'=>'required|max:255'
        ];
    }
    public function messages()
    {
        return ['post.required'=>'the post field cannot be empty',
            'post.max'=>'the max character is 255' ]; // TODO: Change the autogenerated stub
    }

}
